global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: puneet@leewayhertz.com
    from: abctesting166@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: abctesting166@gmail.com
    auth_identity: abctesting166@gmail.com
    auth_password: bbdxuwwfmjyofuxm
    send_resolved: true
